[theme]
base = "dark"
primaryColor = "#78F6BD"
backgroundColor = "#07100E"
secondaryBackgroundColor = "#0D1D19"
textColor = "#EFFFF8"
font = "sans-serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
