[theme]
base = "light"
primaryColor = "#2368E8"
backgroundColor = "#F4F7FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0C1830"
font = "sans-serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
